spring:
  datasource:
    url: "jdbc:mysql://uhx4az1epjrqlwfa:t1ELCK0WEmzoOMQDG1YW@bbm6fx2het5plzfjw0do-mysql.services.clever-cloud.com:3306/bbm6fx2het5plzfjw0do"
    username: "uhx4az1epjrqlwfa"
    password: "t1ELCK0WEmzoOMQDG1YW"
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
jwt:
  secret: MTdiNjY2MTctODI3Ni00ZGM4LWIzMWUtZjI0NGFjMDcxOTJk
  expiration: 9000
server:
  port: 10000